### ISSUE TITLE
Selecting size as the only column in the topic details throws an exception

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1051]
If you go inside a topic, list messages and configure the table so that it should only show the size column an exception is thrown:

![ss-Lj2oZo2C](https://github.com/redpanda-data/console/assets/23424570/66c8d91f-551e-4115-a8fa-6b3cc491b251)

```
Uncaught runtime errors:
×
ERROR
Cannot set properties of undefined (setting 'size')
TypeError: Cannot set properties of undefined (setting 'size')
    at http://localhost:3000/static/js/src_state_backendApi_ts.chunk.js:31567:46
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:10041:14
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:10372:19
    at trackDerivedFunction (http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:13088:18)
    at Reaction.track (http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:13607:18)
    at useObserver (http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:10370:16)
    at observerComponent (http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_ApiOutlined_js-node_modules_ant-design_icons_e-be71cb.chunk.js:10040:69)
    at renderWithHooks (http://localhost:3000/static/js/vendors-node_modules_react-dom_index_js.chunk.js:14150:22)
    at updateFunctionComponent (http://localhost:3000/static/js/vendors-node_modules_react-dom_index_js.chunk.js:17032:24)
    at updateSimpleMemoComponent (http://localhost:3000/static/js/vendors-node_modules_react-dom_index_js.chunk.js:16894:14)
```

**Comment by jvorcak** [comment]
Fixed in https://github.com/redpanda-data/console/pull/1052
