### ISSUE TITLE
Exception while entering invalid RegEx on ConsumerGroup page

### ISSUE THREAD

**Issue by rsommer** [redpanda-data/console#1080]
When entering an invalid RegEx (`*` instead of `.*`) on the consumer group page you end up with:
```
Type:
SyntaxError

Message:
Invalid regular expression: /*/i: Nothing to repeat

Stack (Decoded):
GroupList.render (components/pages/consumers/Group.List.tsx:71:34)
func (../node_modules/mobx/src/core/action.ts:155:15)
_allowStateChanges (../node_modules/mobx-react/src/observerClass.ts:174:28)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react/src/observerClass.ts:170:17)
render (../node_modules/mobx-react/src/observerClass.ts:72:20)
render (../node_modules/react-dom/cjs/react-dom.profiling.min.js:221:211)
Oj (../node_modules/react-dom/cjs/react-dom.profiling.min.js:220:148)

Stack (Raw):
SyntaxError: Invalid regular expression: /*/i: Nothing to repeat
    at new RegExp (<anonymous>)
    at GroupList.render (http://localhost:8080/static/js/784.07ef67db.chunk.js:1:194253)
    at allowStateChanges (http://localhost:8080/static/js/62.1467098f.chunk.js:2:100253)
    at http://localhost:8080/static/js/62.1467098f.chunk.js:2:83407
    at trackDerivedFunction (http://localhost:8080/static/js/62.1467098f.chunk.js:2:107240)
    at Reaction.track (http://localhost:8080/static/js/62.1467098f.chunk.js:2:112203)
    at GroupList.reactiveRender [as render] (http://localhost:8080/static/js/62.1467098f.chunk.js:2:83375)
    at l.render (http://localhost:8080/static/js/62.1467098f.chunk.js:2:82168)
    at Oj (http://localhost:8080/static/js/683.fd976339.chunk.js:2:81210)
    at Mj (http://localhost:8080/static/js/683.fd976339.chunk.js:2:80983)

Components:

    at GroupList (http://localhost:8080/static/js/784.07ef67db.chunk.js:1:192776)
    at Route (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:163563)
    at Switch (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:164637)
    at PresenceChild (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:521031)
    at AnimatePresence (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:521920)
    at RouteView
    at observerComponent (http://localhost:8080/static/js/62.1467098f.chunk.js:2:78268)
    at div
    at observerComponent (http://localhost:8080/static/js/62.1467098f.chunk.js:2:78268)
    at main
    at http://localhost:8080/static/js/324.2bab6574.chunk.js:2:12610
    at ChakraComponent (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:431129)
    at Container2 (http://localhost:8080/static/js/293.57219ddb.chunk.js:2:152023)
    at div
    at http://localhost:8080/static/js/324.2bab6574.chunk.js:2:12610
    at ChakraComponent (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:431129)
    at Grid2 (http://localhost:8080/static/js/293.57219ddb.chunk.js:2:143823)
    at Switch (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:164637)
    at RequireAuth (http://localhost:8080/static/js/439.1155fb2b.chunk.js:1:37006)
    at ErrorBoundary (http://localhost:8080/static/js/439.1155fb2b.chunk.js:1:1215)
    at EnvironmentProvider (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:380381)
    at ColorModeProvider (http://localhost:8080/static/js/293.57219ddb.chunk.js:2:45664)
    at ThemeProvider (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:13006)
    at ThemeProvider (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:434740)
    at ChakraProvider (http://localhost:8080/static/js/293.57219ddb.chunk.js:2:48740)
    at ChakraProvider2 (http://localhost:8080/static/js/293.57219ddb.chunk.js:2:49375)
    at Router (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:160423)
    at BrowserRouter (http://localhost:8080/static/js/324.2bab6574.chunk.js:2:154918)
    at observerComponent (http://localhost:8080/static/js/62.1467098f.chunk.js:2:78268)

Environment:
NODE_ENV        : production
GIT_SHA         : ac168392c5063b67c6d01b54cb54ffac7877f622
GIT_REF         : master
BUILD_TIMESTAMP : 1706892931
PLATFORM_VERSION: v23.3
BUILT_FROM_PUSH : false

Location:
Protocol: http:
Path    : /groups
Search  : 
Hash    : 

```
Even after clearing all browser caches (this is on Chrome), the page stays white. Javascript Console:
```
SyntaxError: Invalid regular expression: /*/i: Nothing to repeat (at Group.List.tsx:71:35)
    at new RegExp (<anonymous>)
    at GroupList.render (Group.List.tsx:71:35)
    at allowStateChanges (action.ts:155:16)
    at observerClass.ts:174:29
    at trackDerivedFunction (derivation.ts:183:24)
    at Reaction.track (reaction.ts:137:24)
    at GroupList.reactiveRender [as render] (observerClass.ts:170:18)
    at l.render (observerClass.ts:72:21)
    at Oj (react-dom.profiling.min.js:221:212)
    at Mj (react-dom.profiling.min.js:220:149)
 ```

When trying to manually override the `q` parameter:
```
Uncaught Error: _history should not be overwritten
    at AppGlobal.set (appGlobal.ts:23:34)
    at HistorySetter.tsx:8:15
    at li (react-dom.profiling.min.js:182:137)
    at Jl (react-dom.profiling.min.js:320:343)
    at Il (react-dom.profiling.min.js:306:129)
    at Hl (react-dom.profiling.min.js:305:303)
    at vl (react-dom.profiling.min.js:305:158)
    at Al (react-dom.profiling.min.js:295:111)
    at tl (react-dom.profiling.min.js:293:90)
    at J (scheduler.production.min.js:13:203)
```

**Comment by weeco** [comment]
Fixed via https://github.com/redpanda-data/console/pull/1081
