### ISSUE TITLE
gettting this issue when accessing to /groups

### ISSUE THREAD

**Issue by nicolasandreoli** [redpanda-data/console#1332]
```
Type:
SyntaxError

Message:
Invalid regular expression: /70abf62ce861 (tag: contacts_interactionstatsconsumer-1.2.17, tag: contacts_interactionscontactsconsumer-1.3.24, tag: contacts_emailcontactsconsumer-1.0.1, tag: 20240715-132641-master-verified) migrate to contacts-fct-contactevents-v2 (#106149) da191eff28e2 (tag: leadsplatform_leadcore-0.1.169) [BG-12347] Lead Platform - Fix assigneeID field (#105414) 8eb699650a3b (tag: schedulercreator_cronjob-8eb699650a3b, tag: 20240704-222407-master-verified) [BG-12400] Lead Platform - Removed integration test in lead core (#105874) 3f72674fb382 (tag: 20240703-132504-master-verified) [BG-12400] Lead Platform - Changed agentID lead-core integration test (#105571) bb5e2702886f (tag: searchinfra_suibmobilefilterv2-20240613-122311, tag: 20240613-122949-master-verified) [BG-12087]: lead-core: propagate anonymousId to LeadContactAssociatedEvent (#104830) 21f5b32dc282 (tag: search_parentsearchserver-20240430083000, tag: media_andromeda-21f5b32dc282, tag: leadsplatform_leadcore-0.1.159, tag: leadsplatform_leadagentmatching-1.6.97, tag: 20240430-123000-master-verified) fix BUILD files (#102471) 82de05cd24ed (tag: leadsplatform_leadcore-0.1.158, tag: leadsplatform_leadagentmatching-1.6.96) [BG-11087] lead_common: move people parsing logic to lead_common (#102041) (END)/i: Range out of order in character class

Stack (Decoded):
GroupList.render (components/pages/consumers/Group.List.tsx:71:34)
func (../node_modules/mobx/src/core/action.ts:155:15)
_allowStateChanges (../node_modules/mobx-react/src/observerClass.ts:174:28)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react/src/observerClass.ts:170:17)
render (../node_modules/mobx-react/src/observerClass.ts:72:20)
render (../node_modules/react-dom/cjs/react-dom.profiling.min.js:221:211)
Oj (../node_modules/react-dom/cjs/react-dom.profiling.min.js:220:148)

Stack (Raw):
SyntaxError: Invalid regular expression: /70abf62ce861 (tag: contacts_interactionstatsconsumer-1.2.17, tag: contacts_interactionscontactsconsumer-1.3.24, tag: contacts_emailcontactsconsumer-1.0.1, tag: 20240715-132641-master-verified) migrate to contacts-fct-contactevents-v2 (#106149) da191eff28e2 (tag: leadsplatform_leadcore-0.1.169) [BG-12347] Lead Platform - Fix assigneeID field (#105414) 8eb699650a3b (tag: schedulercreator_cronjob-8eb699650a3b, tag: 20240704-222407-master-verified) [BG-12400] Lead Platform - Removed integration test in lead core (#105874) 3f72674fb382 (tag: 20240703-132504-master-verified) [BG-12400] Lead Platform - Changed agentID lead-core integration test (#105571) bb5e2702886f (tag: searchinfra_suibmobilefilterv2-20240613-122311, tag: 20240613-122949-master-verified) [BG-12087]: lead-core: propagate anonymousId to LeadContactAssociatedEvent (#104830) 21f5b32dc282 (tag: search_parentsearchserver-20240430083000, tag: media_andromeda-21f5b32dc282, tag: leadsplatform_leadcore-0.1.159, tag: leadsplatform_leadagentmatching-1.6.97, tag: 20240430-123000-master-verified) fix BUILD files (#102471) 82de05cd24ed (tag: leadsplatform_leadcore-0.1.158, tag: leadsplatform_leadagentmatching-1.6.96) [BG-11087] lead_common: move people parsing logic to lead_common (#102041) (END)/i: Range out of order in character class
    at new RegExp (<anonymous>)
    at GroupList.render (http://localhost:8001/static/js/784.07ef67db.chunk.js:1:194253)
    at allowStateChanges (http://localhost:8001/static/js/62.1467098f.chunk.js:2:100253)
    at http://localhost:8001/static/js/62.1467098f.chunk.js:2:83407
    at trackDerivedFunction (http://localhost:8001/static/js/62.1467098f.chunk.js:2:107240)
    at Reaction.track (http://localhost:8001/static/js/62.1467098f.chunk.js:2:112203)
    at GroupList.reactiveRender [as render] (http://localhost:8001/static/js/62.1467098f.chunk.js:2:83375)
    at l.render (http://localhost:8001/static/js/62.1467098f.chunk.js:2:82168)
    at Oj (http://localhost:8001/static/js/683.fd976339.chunk.js:2:81210)
    at Mj (http://localhost:8001/static/js/683.fd976339.chunk.js:2:80983)

Components:

    at GroupList (http://localhost:8001/static/js/784.07ef67db.chunk.js:1:192776)
    at Route (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:163563)
    at Switch (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:164637)
    at PresenceChild (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:521031)
    at AnimatePresence (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:521920)
    at RouteView
    at observerComponent (http://localhost:8001/static/js/62.1467098f.chunk.js:2:78268)
    at div
    at observerComponent (http://localhost:8001/static/js/62.1467098f.chunk.js:2:78268)
    at main
    at http://localhost:8001/static/js/324.2bab6574.chunk.js:2:12610
    at ChakraComponent (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:431129)
    at Container2 (http://localhost:8001/static/js/293.57219ddb.chunk.js:2:152023)
    at div
    at http://localhost:8001/static/js/324.2bab6574.chunk.js:2:12610
    at ChakraComponent (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:431129)
    at Grid2 (http://localhost:8001/static/js/293.57219ddb.chunk.js:2:143823)
    at Switch (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:164637)
    at RequireAuth (http://localhost:8001/static/js/439.1155fb2b.chunk.js:1:37006)
    at ErrorBoundary (http://localhost:8001/static/js/439.1155fb2b.chunk.js:1:1215)
    at EnvironmentProvider (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:380381)
    at ColorModeProvider (http://localhost:8001/static/js/293.57219ddb.chunk.js:2:45664)
    at ThemeProvider (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:13006)
    at ThemeProvider (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:434740)
    at ChakraProvider (http://localhost:8001/static/js/293.57219ddb.chunk.js:2:48740)
    at ChakraProvider2 (http://localhost:8001/static/js/293.57219ddb.chunk.js:2:49375)
    at Router (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:160423)
    at BrowserRouter (http://localhost:8001/static/js/324.2bab6574.chunk.js:2:154918)
    at observerComponent (http://localhost:8001/static/js/62.1467098f.chunk.js:2:78268)

Environment:
NODE_ENV        : production
GIT_SHA         : ac168392c5063b67c6d01b54cb54ffac7877f622
GIT_REF         : master
BUILD_TIMESTAMP : 1706892931
PLATFORM_VERSION: v23.3
BUILT_FROM_PUSH : false

Location:
Protocol: http:
Path    : /groups
Search  : 
Hash    : 

```

**Comment by weeco** [comment]
Could you please try the latest v2.6.1 version? In the past months we pushed a fix for searches with regex chars. I'm not entirely sure if that was supposed to be included in the version you are running. If the issues still exists in v2.6.1 we'll have another look.

**Comment by nicolasandreoli** [comment]
It's working with the 2.6 version. Thanks!
