### ISSUE TITLE
Error while opening a topic information page in the same page (opening in a new tab is stable) 

### ISSUE THREAD

**Issue by dtr-beast** [redpanda-data/console#1347]
Message:
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack (Decoded):
Error (../node_modules/react-dom/cjs/react-dom.profiling.min.js:183:313)
si (../node_modules/react-dom/cjs/react-dom.profiling.min.js:194:23)
useMemo (../node_modules/react/cjs/react.production.min.js:25:207)
useMemo (hooks/usePaginationParams.ts:23:11)
uiState (components/pages/topics/Tab.Partitions.tsx:44:49)
render (../node_modules/mobx-react-lite/src/observer.ts:104:33)
fn (../node_modules/mobx-react-lite/src/useObserver.ts:126:24)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react-lite/src/useObserver.ts:124:17)

Stack (Raw):
at si (http://localhost:8080/static/js/683.fd976339.chunk.js:2:66168)
    at Object.Ti [as useMemo] (http://localhost:8080/static/js/683.fd976339.chunk.js:2:69891)
    at t.useMemo (http://localhost:8080/static/js/2791.419d6a0e.chunk.js:2:6270)
    at usePaginationParams (http://localhost:8080/static/js/4280.caf35915.chunk.js:1:693982)
    at http://localhost:8080/static/js/4280.caf35915.chunk.js:1:654456
    at http://localhost:8080/static/js/9249.9b198061.chunk.js:2:76668
    at http://localhost:8080/static/js/9249.9b198061.chunk.js:2:75742
    at trackDerivedFunction (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:105612)
    at Reaction.track (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:110575)
    at useObserver (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:75718)

Components:

    at observerComponent (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:76637)
    at div
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at TabPanel2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:218391)
    at div
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at TabPanels2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:218667)
    at div
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at Tabs2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:217274)
    at Tabs (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:273056)
    at Tabs (http://localhost:8080/static/js/4280.caf35915.chunk.js:1:14602)
    at section
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at Section (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:264803)
    at Section
    at div
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:346490
    at div
    at VisualElementHandler (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:557990)
    at MotionComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:558862)
    at PageContent (http://localhost:8080/static/js/4280.caf35915.chunk.js:1:7938)
    at TopicDetails (http://localhost:8080/static/js/4280.caf35915.chunk.js:1:658331)
    at Route (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:165427)
    at Switch (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:166501)
    at PresenceChild (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:549680)
    at AnimatePresence (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:550569)
    at RouteView
    at observerComponent (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:76637)
    at div
    at observerComponent (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:76637)
    at main
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at Container2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:131977)
    at div
    at http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:12611
    at ChakraComponent (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:453784)
    at Grid2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:123777)
    at Switch (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:166501)
    at RequireAuth (http://localhost:8080/static/js/9439.50b439a6.chunk.js:1:37403)
    at ErrorBoundary (http://localhost:8080/static/js/9439.50b439a6.chunk.js:1:1216)
    at EnvironmentProvider (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:403055)
    at ColorModeProvider (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:45978)
    at ThemeProvider (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:13007)
    at ThemeProvider (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:457395)
    at ChakraProvider (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:49054)
    at ChakraProvider2 (http://localhost:8080/static/js/3388.0bf0fdf9.chunk.js:2:49689)
    at Router (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:162287)
    at BrowserRouter (http://localhost:8080/static/js/4503.5256a2d8.chunk.js:2:156749)
    at observerComponent (http://localhost:8080/static/js/9249.9b198061.chunk.js:2:76637)

Environment:
NODE_ENV        : production
GIT_SHA         : 42e56574aa1ff618083a3199ea869242b110fb59
GIT_REF         : master
BUILD_TIMESTAMP : 1720621253
PLATFORM_VERSION: v24.1
BUILT_FROM_PUSH : false

Location:
Protocol: http:
Path    : /topics/sales
Search  : 
Hash    : #partitions

**Comment by weeco** [comment]
I believe this is already fixed but not yet released. Would you mind trying this Docker image: `redpandadata/console-unstable:master-a786b3c` ?
