### ISSUE TITLE
Console crash when attempting to navigate to Topic

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/console#1442]
Sorry for the copy-pasta issue here...the "Copy Info" button wasn't working for me:

```
Message
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack (Decoded)
Error (../node_modules/react-dom/cjs/react-dom.profiling.min.js:183:313)
si (../node_modules/react-dom/cjs/react-dom.profiling.min.js:194:23)
useMemo (../node_modules/react/cjs/react.production.min.js:25:207)
useMemo (hooks/usePaginationParams.ts:23:11)
uiState (components/pages/topics/Tab.Partitions.tsx:44:49)
render (../node_modules/mobx-react-lite/src/observer.ts:104:33)
fn (../node_modules/mobx-react-lite/src/useObserver.ts:126:24)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react-lite/src/useObserver.ts:124:17)

Stack (Raw)
at si (http://fedora-linux:8080/static/js/683.fd976339.chunk.js:2:66168)
at Object.Ti [as useMemo] (http://fedora-linux:8080/static/js/683.fd976339.chunk.js:2:69891)
at http://fedora-linux:8080/static/js/791.d81f3f42.chunk.js:2:6269
at usePaginationParams (http://fedora-linux:8080/static/js/994.db25c395.chunk.js:1:550517)
at http://fedora-linux:8080/static/js/994.db25c395.chunk.js:1:510991
at http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:78299
at http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:77373
at trackDerivedFunction (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:107240)
at Reaction.track (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:112203)
at useObserver (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:77349)

Components
at observerComponent (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:78268)
at div
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at TabPanel2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:218390)
at div
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at TabPanels2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:218666)
at div
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at Tabs2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:217273)
at Tabs (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:273055)
at Tabs (http://fedora-linux:8080/static/js/994.db25c395.chunk.js:1:14598)
at section
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at Section (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:264802)
at Section
at div
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:363941
at div
at VisualElementHandler (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:575575)
at MotionComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:576447)
at PageContent (http://fedora-linux:8080/static/js/994.db25c395.chunk.js:1:7934)
at TopicDetails (http://fedora-linux:8080/static/js/994.db25c395.chunk.js:1:514866)
at Route (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:165521)
at Switch (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:166595)
at PresenceChild (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:567265)
at AnimatePresence (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:568154)
at RouteView
at observerComponent (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:78268)
at div
at observerComponent (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:78268)
at main
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at Container2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:131976)
at div
at http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:12610
at ChakraComponent (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:471336)
at Grid2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:123776)
at Switch (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:166595)
at RequireAuth (http://fedora-linux:8080/static/js/439.83ea5ce2.chunk.js:1:37401)
at ErrorBoundary (http://fedora-linux:8080/static/js/439.83ea5ce2.chunk.js:1:1214)
at EnvironmentProvider (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:420588)
at ColorModeProvider (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:45977)
at ThemeProvider (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:13006)
at ThemeProvider (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:474947)
at ChakraProvider (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:49053)
at ChakraProvider2 (http://fedora-linux:8080/static/js/388.193415d8.chunk.js:2:49688)
at Router (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:162381)
at BrowserRouter (http://fedora-linux:8080/static/js/503.4eb6213c.chunk.js:2:156843)
at observerComponent (http://fedora-linux:8080/static/js/62.045b48c9.chunk.js:2:78268)

Environment
NODE_ENV        : production
GIT_SHA         : 8139cec7ad02139e1eaabef280117e70cbc8fcc4
GIT_REF         : master
BUILD_TIMESTAMP : 1714503303
PLATFORM_VERSION: v23.3
BUILT_FROM_PUSH : false

Location
Protocol: http:
Path    : /topics/click
Search  : 
Hash    : #partitions
```

Clicking "Dismiss" causes it to properly load the Topics page.

This topic contains data produced using a Python client and encoded as Avro using the following value schema:

```json
{
    "type": "record",
    "name": "Click",
    "namespace": "com.redpanda.examples.avro",
    "fields": [
        {
            "name": "user_id",
            "type": "int"
        },
        {
            "name": "event_type",
            "type": "string"
        },
        {
            "name": "ts_millis",
            "type": "long"
        }
    ]
}
```

Afterwards, the page works fine until I reload my browser and navigate again to the topic.

**Comment by weeco** [comment]
@voutilad It seems you are using an older version (built end of April). Could you please re-test with the latest Console version (2.7.2 or built against master). If this is still happening, it would be helpful to see the backend responses for the partitions request.
