### ISSUE TITLE
Whenever I go to see a topic I get the following error : "Rendered more hooks than during the previous render." After refreshing a few times the Topic Details show up

### ISSUE THREAD

**Issue by devansh-hitwicket** [redpanda-data/console#1471]
I get the following error:

Message:
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack (Decoded):
Error (../node_modules/react-dom/cjs/react-dom.profiling.min.js:183:313)
si (../node_modules/react-dom/cjs/react-dom.profiling.min.js:194:23)
useMemo (../node_modules/react/cjs/react.production.min.js:25:207)
useMemo (hooks/usePaginationParams.ts:23:11)
uiState (components/pages/topics/Tab.Partitions.tsx:44:49)
render (../node_modules/mobx-react-lite/src/observer.ts:104:33)
fn (../node_modules/mobx-react-lite/src/useObserver.ts:126:24)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react-lite/src/useObserver.ts:124:17)

Stack (Raw):
at si (https://rp-console.hitwicketsuperstars.com/static/js/683.fd976339.chunk.js:2:66168)
    at Object.Ti [as useMemo] (https://rp-console.hitwicketsuperstars.com/static/js/683.fd976339.chunk.js:2:69891)
    at https://rp-console.hitwicketsuperstars.com/static/js/791.d81f3f42.chunk.js:2:6269
    at usePaginationParams (https://rp-console.hitwicketsuperstars.com/static/js/536.9907d6c7.chunk.js:1:511058)
    at https://rp-console.hitwicketsuperstars.com/static/js/536.9907d6c7.chunk.js:1:471530
    at https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:78299
    at https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:77373
    at trackDerivedFunction (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:107240)
    at Reaction.track (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:112203)
    at useObserver (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:77349)

Components:

    at observerComponent (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:78268)
    at div
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at TabPanel2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:218454)
    at div
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at TabPanels2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:218730)
    at div
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at Tabs2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:217337)
    at Tabs (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:273499)
    at Tabs (https://rp-console.hitwicketsuperstars.com/static/js/536.9907d6c7.chunk.js:1:14609)
    at section
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at Section (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:265262)
    at Section
    at div
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:364279
    at div
    at VisualElementHandler (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:574000)
    at MotionComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:574872)
    at PageContent (https://rp-console.hitwicketsuperstars.com/static/js/536.9907d6c7.chunk.js:1:7938)
    at TopicDetails (https://rp-console.hitwicketsuperstars.com/static/js/536.9907d6c7.chunk.js:1:475405)
    at Route (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:166064)
    at Switch (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:167138)
    at PresenceChild (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:565690)
    at AnimatePresence (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:566579)
    at RouteView
    at observerComponent (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:78268)
    at div
    at observerComponent (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:78268)
    at main
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at Container2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:132040)
    at div
    at https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:12610
    at ChakraComponent (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:471674)
    at Grid2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:123840)
    at Switch (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:167138)
    at RequireAuth (https://rp-console.hitwicketsuperstars.com/static/js/439.ff1e58d0.chunk.js:1:37402)
    at ErrorBoundary (https://rp-console.hitwicketsuperstars.com/static/js/439.ff1e58d0.chunk.js:1:1215)
    at EnvironmentProvider (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:420926)
    at ColorModeProvider (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:45720)
    at ThemeProvider (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:13006)
    at ThemeProvider (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:475285)
    at ChakraProvider (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:48796)
    at ChakraProvider2 (https://rp-console.hitwicketsuperstars.com/static/js/731.ecdf9baf.chunk.js:2:49431)
    at Router (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:162924)
    at BrowserRouter (https://rp-console.hitwicketsuperstars.com/static/js/826.4c694c92.chunk.js:2:157419)
    at observerComponent (https://rp-console.hitwicketsuperstars.com/static/js/62.32f36fb7.chunk.js:2:78268)

Environment:
NODE_ENV       : production
GIT_SHA        : 303b7b5cde4d14ba02d68558e7c419c50bc401a8
GIT_REF        : master
BUILD_TIMESTAMP: 1712675364
BUILT_FROM_PUSH: false

Location:
Protocol: https:
Path    : /topics/lobby-raw-events
Search  : 
Hash    : #partitions

**Comment by rikimaru0345** [comment]
Is there any pattern to when you see this popping up?
Does it happen for every topic or just one?
Are there specific messages that are being shown that might trigger this?

Do you have a HAR for messages request when this happens?

**Comment by e8tg001** [comment]
Me too. Only used after the first installation.

**Comment by weeco** [comment]
I can see that the original stack was provided by a version built in April 2024. Could you please try the latest version and see if this issue still exists?
