### ISSUE TITLE
Erreur non trouvée

### ISSUE THREAD

**Issue by SALMAbrh** [redpanda-data/console#1571]
Échec de l'exécution de « removeChild » sur « Node » : le nœud à supprimer n'est pas un enfant de ce nœud.

**Comment by SALMAbrh** [comment]
Type:
NotFoundError

Message:
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Stack (Decoded):
uQ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:85126)
uW (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:84810)
uQ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:85801)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86367)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86765)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)

Stack (Raw):
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uQ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:85126)
    at uW (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:84810)
    at uQ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:85801)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86367)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86765)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:87947)
    at u$ (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86517)

Components:

    at p
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86827)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at div
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:2:35239
    at div
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:2:35239
    at div
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at div
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at A5 (https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:281:3399)
    at A3 (https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:281:763)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at p (https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/9569.d2f873eb.js:2:824158)
    at A7 (https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:281:3899)
    at https://ctjjhqafdq8asdnsme90.console.us-east-1.mpx.prd.cloud.redpanda.com/static/js/async/7843.42dc0924.js:281:4369
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)
    at uK (https://cloud.redpanda.com/static/js/async/7987.4c5330f7.js:2:86630)

Environment:
GIT_SHA         : ca48c425e5b43a1b01a9c318328a536e636555f5
GIT_REF         : master
BUILD_TIMESTAMP : 1733934164
PLATFORM_VERSION: v24.3
BUILT_FROM_PUSH : true

Location:
Protocol: https:
Path    : /clusters/ctjjhqafdq8asdnsme90/topics/input_topic
Search  : ?p=-1&s=50&o=-1
Hash    : #messages

**Comment by weeco** [comment]
Please submit your issue in English.
