### ISSUE TITLE
Rendering Error on Consumer Group

### ISSUE THREAD

**Issue by Trigzorgs** [redpanda-data/console#438]
Hello

I'am experiencing an error in Kowl, when i'am trying to view consumers in a consumer group. This happens when clicking anyone of our groups

Type:
TypeError

Message:
Cannot read properties of null (reading 'length')

Stack (Decoded):
render (components/pages/consumers/Group.Details.tsx:120:102)
sum (utils/arrayExtensions.ts:113:43)
sum (utils/arrayExtensions.ts:113:16)
render (components/pages/consumers/Group.Details.tsx:120:76)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)

Stack (Raw):
TypeError: Cannot read properties of null (reading 'length')
    at http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:287746
    at http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:17888
    at Array.reduce (<anonymous>)
    at Array.sum (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:17857)
    at n.value (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:287707)
    at Le (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:13429)
    at http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:63503
    at Xe (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:19362)
    at t.track (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:23698)
    at n.l [as render] (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:63468)

Components:

    at n (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:285587)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:121185)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:122136)
    at u (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:960844)
    at m (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:961553)
    at Wi
    at n (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:422258)
    at main
    at m (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:603978)
    at a (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:603808)
    at section
    at http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:604238
    at a (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:603808)
    at l (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:59792)
    at section
    at http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:604238
    at a (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:603808)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:121185)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:122136)
    at n (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:433564)
    at n (http://localhost:8090/static/js/main.b8b857ee.chunk.js:1:465492)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:118479)
    at t (http://localhost:8090/static/js/2.b8fdf585.chunk.js:2:348858)

Environment:
NODE_ENV       : production
GIT_SHA        : 598117cf7d3ef49e82ad9e7424a08858b3e60216
GIT_REF        : v1.5.0
TIMESTAMP      : 1636580476
BUILT_FROM_PUSH: false
appName        : Kowl

Location:
Protocol: http:
Path    : /groups/<group name omitted>
Search  : 
Hash    :

**Comment by weeco** [comment]
Hello,
you are using an old version. Please try again with the latest Console version and see if the problem still persists.

**Comment by Trigzorgs** [comment]
fixed the issue thanks
