### ISSUE TITLE
The web page will report an error when accessing a topic with an offline partition.

### ISSUE THREAD

**Issue by cobolbaby** [redpanda-data/console#980]
![2023-12-26 13-28-59屏幕截图](https://github.com/redpanda-data/console/assets/11460848/491fb17d-8d5b-4999-bfe9-5c8058f0e835)

```
Type:
TypeError

Message:
Cannot read properties of null (reading 'distinct')

Stack (Decoded):
distinct (components/misc/BrokerList.tsx:42:43)
func (../node_modules/mobx/src/core/action.ts:155:15)
_allowStateChanges (../node_modules/mobx-react/src/observerClass.ts:174:28)
call (../node_modules/mobx/src/core/derivation.ts:183:23)
trackDerivedFunction (../node_modules/mobx/src/core/reaction.ts:137:23)
track (../node_modules/mobx-react/src/observerClass.ts:170:17)
render (../node_modules/mobx-react/src/observerClass.ts:72:20)
render (../node_modules/react-dom/cjs/react-dom.profiling.min.js:221:211)
Oj (../node_modules/react-dom/cjs/react-dom.profiling.min.js:220:148)
Mj (../node_modules/react-dom/cjs/react-dom.profiling.min.js:322:171)

Stack (Raw):
TypeError: Cannot read properties of null (reading 'distinct')
    at BrokerList.render (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:1230)
    at allowStateChanges (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:813855)
    at https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:797126
    at trackDerivedFunction (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:820842)
    at Reaction.track (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:825667)
    at BrokerList.reactiveRender [as render] (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:797094)
    at l.render (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:795887)
    at Oj (https://infra-kafka-kowl.itc.inventec.net/static/js/683.fd976339.chunk.js:2:81210)
    at Mj (https://infra-kafka-kowl.itc.inventec.net/static/js/683.fd976339.chunk.js:2:80983)
    at Jl (https://infra-kafka-kowl.itc.inventec.net/static/js/683.fd976339.chunk.js:2:130541)

Components:

    at BrokerList (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:953)
    at td
    at Cell (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1107913)
    at https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1111028
    at tr
    at BodyRow (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1116761)
    at tbody
    at Provider (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1111860)
    at Body (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1120118)
    at table
    at div
    at div
    at https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1128403
    at div
    at Table (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:1128543)
    at div
    at div
    at Spin (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:463318)
    at SpinFC (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:465277)
    at div
    at InternalTable (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:514000)
    at TopicPartitions (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:451127)
    at article
    at div
    at Tabs (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:29783)
    at section
    at https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:12610
    at ChakraComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:222225)
    at Section (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:490220)
    at Section
    at div
    at https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:12610
    at ChakraComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:222225)
    at https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:197006
    at div
    at VisualElementHandler (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:308040)
    at MotionComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:308912)
    at PageContent (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:24248)
    at TopicDetails (https://infra-kafka-kowl.itc.inventec.net/static/js/506.8f55509e.chunk.js:1:455684)
    at Route (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:103400)
    at Switch (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:104474)
    at PresenceChild (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:299730)
    at AnimatePresence (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:300619)
    at RouteView
    at ErrorDisplay (https://infra-kafka-kowl.itc.inventec.net/static/js/733.f66b3d16.chunk.js:1:24098)
    at div
    at observerComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:791987)
    at main
    at https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:12610
    at ChakraComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:222225)
    at Container2 (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:205300)
    at div
    at https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:12610
    at ChakraComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:222225)
    at Grid2 (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:193348)
    at Switch (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:104474)
    at RequireAuth (https://infra-kafka-kowl.itc.inventec.net/static/js/733.f66b3d16.chunk.js:1:39593)
    at ErrorBoundary (https://infra-kafka-kowl.itc.inventec.net/static/js/733.f66b3d16.chunk.js:1:746)
    at EnvironmentProvider (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:65951)
    at ColorModeProvider (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:62534)
    at ThemeProvider (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:13006)
    at ThemeProvider (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:60417)
    at ChakraProvider (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:66548)
    at ChakraProvider2 (https://infra-kafka-kowl.itc.inventec.net/static/js/550.374d74ba.chunk.js:2:81845)
    at Router (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:100260)
    at BrowserRouter (https://infra-kafka-kowl.itc.inventec.net/static/js/910.aa630b19.chunk.js:2:94756)
    at observerComponent (https://infra-kafka-kowl.itc.inventec.net/static/js/178.f9517ba1.chunk.js:2:791987)

Environment:
NODE_ENV        : production
GIT_SHA         : 1db8cedf2d9d8ac087961476cf9e885ad5e1118a
GIT_REF         : master
BUILD_TIMESTAMP : 1694701166
PLATFORM_VERSION: v23.2
BUILT_FROM_PUSH : false

Location:
Protocol: https:
Path    : /topics/f3-cpu-fis-result
Search  : ?p=-1&s=50&o=-1
Hash    : #partitions

```

**Comment by weeco** [comment]
Thanks for this report. Since this is a bit harder to reproduce, do you happen to have the network response for the broker list available as well? I'll check whether we can add a test for this using the `kfake` package. You should rely on using Console regardless in what conditions the brokers are.

**Comment by cobolbaby** [comment]
One node went offline, causing the several offline partitions.
